[2024-06-25T19:07:12.737+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-25T19:07:12.761+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sp_budget_pipeline.app-sp_budget manual__2024-06-25T19:06:43.005940+00:00 [queued]>
[2024-06-25T19:07:12.768+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sp_budget_pipeline.app-sp_budget manual__2024-06-25T19:06:43.005940+00:00 [queued]>
[2024-06-25T19:07:12.769+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-25T19:07:12.885+0000] {taskinstance.py:2330} INFO - Executing <Task(DockerOperator): app-sp_budget> on 2024-06-25 19:06:43.005940+00:00
[2024-06-25T19:07:12.903+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=80) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-25T19:07:12.907+0000] {standard_task_runner.py:63} INFO - Started process 81 to run task
[2024-06-25T19:07:12.909+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sp_budget_pipeline', 'app-sp_budget', 'manual__2024-06-25T19:06:43.005940+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/sp_budget_pipeline.py', '--cfg-path', '/tmp/tmpx04mhof3']
[2024-06-25T19:07:12.911+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask app-sp_budget
[2024-06-25T19:07:13.037+0000] {task_command.py:426} INFO - Running <TaskInstance: sp_budget_pipeline.app-sp_budget manual__2024-06-25T19:06:43.005940+00:00 [running]> on host 298ae34a2ca3
[2024-06-25T19:07:13.252+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='engenharia-dados' AIRFLOW_CTX_DAG_ID='sp_budget_pipeline' AIRFLOW_CTX_TASK_ID='app-sp_budget' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T19:06:43.005940+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-25T19:06:43.005940+00:00'
[2024-06-25T19:07:13.253+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-25T19:07:13.293+0000] {docker.py:366} INFO - Starting docker container from image etl-engine:latest
[2024-06-25T19:07:13.295+0000] {docker.py:374} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2024-06-25T19:07:17.774+0000] {docker.py:436} INFO - 2024-06-25 19:07:17,774 [ERROR] Invalid engine.
[2024-06-25T19:07:20.872+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-25T19:07:20.989+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=sp_budget_pipeline, task_id=app-sp_budget, run_id=manual__2024-06-25T19:06:43.005940+00:00, execution_date=20240625T190643, start_date=20240625T190712, end_date=20240625T190720
[2024-06-25T19:07:21.173+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-25T19:07:21.191+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-25T19:07:21.247+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
